# Generated by Django 4.1.2 on 2022-10-30 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "contactNo",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=10,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("firstName", models.CharField(max_length=50)),
                ("middleName", models.CharField(blank=True, max_length=50)),
                ("lastName", models.CharField(blank=True, max_length=50)),
                ("dob", models.DateField()),
                ("gender", models.CharField(max_length=6)),
                ("houseNo", models.CharField(max_length=10)),
                ("streetName", models.CharField(max_length=50)),
                ("localityName", models.CharField(max_length=50)),
                ("cityName", models.CharField(max_length=20)),
                ("countryName", models.CharField(max_length=20)),
                ("pinCode", models.DecimalField(decimal_places=0, max_digits=6)),
                ("kycVerified", models.BooleanField(default=False)),
                ("idImageFront", models.ImageField(upload_to="UserID_front")),
                ("idImageBack", models.ImageField(upload_to="UserID_back")),
                ("userPhoto", models.ImageField(upload_to="UserPhoto")),
            ],
        ),
    ]
